name: lints and tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install pytest
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --output-format=github .
        continue-on-error: true
      - name: Run pytest
        run: pytest
